services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGO_URL=mongodb://mongodb:27017/todos
      - HOST_URL=13.60.62.126
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_HOST_URL=13.60.62.126 # Not working
      - REACT_APP_BACKEND_PORT=3000 # Not working

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # rabbitmq port number
      - "15672:15672" # Managment UI
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
