services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  backend:
    image: bobbyem/backend
    container_name: backend
    #build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGO_URL=mongodb://mongodb:27017/todos
      - HOST_URL=13.60.62.126
    volumes:
      - ./backend:/app
      - /app/node_modules

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # rabbitmq port number
      - "15672:15672" # Managment UI
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
